import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const handleFileChange = () => {
    return;
  };

  const handleHeightChange = () => {
    return;
  };

  const handleWidthChange = () => {
    return;
  };

  return (
    <>
      <Head>
        <title>Huchuy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 bg-white px-4 py-16">
          <input type="file" onChange={handleFileChange} />
          <input type="text" onChange={handleHeightChange} />
          <input type="text" onChange={handleWidthChange} />
          <button type="button">Transformar</button>
        </div>
      </main>
    </>
  );
};

export default Home;
